// Generates js/supabaseClient.js from environment variables at build
// time — SUPABASE_URL and SUPABASE_ANON_KEY are read from process.env
// (populated by Vercel's Project Settings → Environment Variables in
// deployment, or from a local .env file via dotenv when run locally),
// never hardcoded in this repo.
//
// The anon key still ends up inside the JS the browser downloads —
// that's unavoidable for a static site and is fine, since it's the
// public anon key (never the service_role key). This just moves the
// real value out of git and into per-environment config.
//
// Run manually with: npm run build
// Vercel runs this automatically (see vercel.json's buildCommand).

import { writeFileSync } from "fs";
import dotenv from "dotenv";

dotenv.config();

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    "Missing SUPABASE_URL and/or SUPABASE_ANON_KEY.\n" +
    "Set them in a local .env file (see .env.example) for local builds, " +
    "or in Vercel → Project Settings → Environment Variables for deployment."
  );
  process.exit(1);
}

const output = `/* =========================================================
   OrenkaFine — Supabase browser client
   AUTO-GENERATED by scripts/build-config.js from SUPABASE_URL /
   SUPABASE_ANON_KEY environment variables — do not edit by hand, and
   do not commit this file (see .gitignore). Run "npm run build" to
   regenerate it after changing those environment variables.
   The anon/public key is safe to expose in frontend code.
   NEVER put the service_role key here.
   ========================================================= */

const SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};
const SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};

// supabase-js is loaded globally via the CDN <script> tag in each HTML page
// (see the script tag added before this file: https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2)
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
`;

writeFileSync(new URL("../js/supabaseClient.js", import.meta.url), output);
console.log("Wrote js/supabaseClient.js from environment variables.");
